
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herlambangsb
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pajang = new javax.swing.JTextField();
        lebar = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hsl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Pajang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 64, 50, 14);

        jLabel2.setText("Lebar");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 102, 50, 14);

        jLabel3.setText("Volume Balok");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(154, 11, 100, 14);

        jLabel4.setText("Tinggi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 50, 14);
        jPanel1.add(pajang);
        pajang.setBounds(92, 61, 50, 30);
        jPanel1.add(lebar);
        lebar.setBounds(92, 99, 50, 30);
        jPanel1.add(tinggi);
        tinggi.setBounds(92, 137, 50, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(92, 175, 70, 23);

        hasil.setEditable(false);
        jPanel1.add(hasil);
        hasil.setBounds(130, 240, 90, 30);

        jLabel5.setText("Hasil");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(161, 216, 50, 14);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(173, 175, 61, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setText("Kubus");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 10, 100, 14);

        jLabel7.setText("Panjang Sisi");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 60, 80, 14);
        jPanel2.add(sisi);
        sisi.setBounds(120, 50, 59, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(70, 120, 80, 23);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(180, 120, 100, 23);

        Hasil.setEditable(false);
        jPanel2.add(Hasil);
        Hasil.setBounds(140, 200, 59, 30);

        jLabel8.setText("Hasil");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(150, 170, 40, 14);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel9.setText("Bola");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(149, 11, 90, 14);

        jLabel10.setText("Jari - jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(24, 69, 60, 14);
        jPanel3.add(jari);
        jari.setBounds(110, 60, 60, 30);

        jButton3.setText("Hitung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(61, 127, 63, 23);

        jButton4.setText("Reset");
        jPanel3.add(jButton4);
        jButton4.setBounds(177, 127, 61, 23);

        jLabel11.setText("Hasil");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(156, 185, 60, 14);

        hsl.setEditable(false);
        jPanel3.add(hsl);
        hsl.setBounds(137, 217, 60, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setBounds(0, 0, 416, 354);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(pajang.getText());
        int l = Integer.parseInt(lebar.getText());
        int t = Integer.parseInt(tinggi.getText());
        int hsl = p*l*t;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok: " + hsl, "volume" ,JOptionPane.WARNING_MESSAGE );
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error:"+e, "gagal",JOptionPane.WARNING_MESSAGE );
        }
        

    }//GEN-LAST:event_hitungActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        pajang.setText("");
        lebar.setText("");
        tinggi.setText("");
        hasil.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sisi.setText("");
        Hasil.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int s = Integer.parseInt(sisi.getText());
        int htng = s*s*s;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus: " + htng, "volume" ,JOptionPane.WARNING_MESSAGE );
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error:"+e, "gagal",JOptionPane.WARNING_MESSAGE );
        }
        Hasil.setText(""+htng);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        float r = Integer.parseInt(jari.getText());
        float vol = (float)(4/3*3.14*r*r*r);
        
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola: " + vol, "volume" ,JOptionPane.WARNING_MESSAGE );
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error:"+e, "gagal",JOptionPane.WARNING_MESSAGE );
            
        }
        
        hsl.setText(""+vol);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField hsl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField pajang;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables
}
